### ISSUE TITLE
/profile page is not working.

### ISSUE THREAD

**Issue by aman-roy** [OmkarPathak/A-Simple-Note-Taking-Web-App#1]

**Comment by OmkarPathak** [comment]
@aman-roy  Can you elaborate the issue? Because it is working for me

**Comment by aman-roy** [comment]
When I am clicking on view all notes, which is basically /profile directory it is giving me an error 500. 

Full error - 

Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by OmkarPathak** [comment]
@aman-roy there is something weird going on. I am able to access each and every page perfectly

**Comment by OmkarPathak** [comment]
Fixed! Thanks for pointing it out :+1:
